name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  consoleapp_folder: ConsoleApp
  tests_folder: Tests

jobs:
  build-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies on ConsoleApp
      run: dotnet restore ${{ env.consoleapp_folder }}
    - name: Build ConsoleApp
      run: dotnet build --no-restore ${{ env.consoleapp_folder }}
    - name: Restore dependencies on Tests
      run: dotnet restore ${{ env.tests_folder }}
    - name: Build Tests
      run: dotnet build --no-restore ${{ env.tests_folder }}
    - name: Perform Tests
      run: dotnet test --no-build --verbosity normal ${{ env.tests_folder }}

  test-coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - name: Perform tests and generate coverage
      run: dotnet test --verbosity normal --collect:"XPlat Code Coverage" ${{ env.tests_folder }}
    - name: Consolidate tests reports
      run: reportgenerator "-reports:${{ env.tests_folder }}/**/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:cobertura
    - name: Publish coverage report to coveralls.io
      uses: codecov/codecov-action@v1
      with:
        files: ./coveragereport/Cobertura.xml
        fail_ci_if_error: true
        verbose: true
        functionalities: recursesubs

