name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  consoleapp_folder: ConsoleApp
  tests_folder: Tests

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ${{ consoleapp_folder }}
    - name: Build
      run: dotnet build --no-restore ${{ consoleapp_folder }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ tests_folder }}
