name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  consoleapp_folder: ConsoleApp
  tests_folder: Tests

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies on ConsoleApp
      run: dotnet restore ${{ env.consoleapp_folder }}
    - name: Build ConsoleApp
      run: dotnet build --no-restore ${{ env.consoleapp_folder }}
    - name: Restore dependencies on Tests
      run: dotnet restore ${{ env.tests_folder }}
    - name: Build Tests
      run: dotnet build --no-restore ${{ env.tests_folder }}
    - name: Perform Tests
      run: dotnet test --no-build --verbosity normal ${{ env.tests_folder }}
