name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  console-app-folder: ConsoleApp
  tests-folder: Tests

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ${{ console-app-folder }}
    - name: Build
      run: dotnet build --no-restore ${{ console-app-folder }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ tests-folder }}
